[build]
# Standard target directory
target-dir = "target"

# Cargo aliases for convenient verbose building
[alias]
vbuild = "build --verbose --message-format=human --timings"
vcheck = "check --verbose --message-format=human"
vtest = "test --verbose"
vrun = "run --verbose"

# Removed forced release mode to allow proper dev builds
# [env]
# CARGO_PROFILE = "release"

# Removed dev profile override to use Cargo.toml settings
# [profile.dev]
# Let Cargo.toml handle dev profile configuration

[profile.release]
# Ensure release profile is optimized
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false